    if cleaned_question == "hello":
        print("Bot: Hello! How can I Help You.")
    elif cleaned_question == "hey":
        print("Bot: hey")
    elif cleaned_question == "Tell me internet password":
        print("")
    elif cleaned_question == "tell me a social media app":
        print("Bot: Here are is a List of Social Media Apps: ")
        print("Facebook link = https://facebook.com")
        print("Twitter link = https://twitter.com")
        print("Instagram link = https://instagram.com")
        print("TikTok link = https://tiktok.com")
        print("YouTube link = https://youtube.com")
        print("WhatsApp link = https://whatsapp.com")
        print("Reddit link = https://reddit.com")
        print("LinkedIn link = https://linkedin.com")
        print("Pinterest link = https://pinterest.com")
        print("Snapchat link = https://snapchat.com")
        print("Tumblr link = https://tumblr.com")
        print("Discord link = https://discord.com")
        print("Vimeo link = https://vimeo.com")
        print("Flickr link = https://flickr.com")
        print("Medium link = https://medium.com")
        print("Periscope link = https://periscope.tv")
        print("Pinterest link = https://pinterest.com")
        print("SoundCloud link = https://soundcloud.com")
        print("Spotify link = https://spotify.com")
        print("Twitch link = https://twitch.tv")
        print("WeChat link = https://weixin.qq.com")
        print("Weibo link = http://weibo.com")
        print("KakaoTalk link = http://story.kakaocorp.com/service/kakaotalk/")
        print("Kik Messenger link = http://kik.me/")
        print("Telegram link = https://telegram.org/")
        print("Viber link = http://viber.com/")
        print("Skype link = https://skype.live/")
        print("Hangouts link = https://hangouts.google.com/")
        print("Google+ link = http://plus.google.com/")
        print("Foursquare link = http://foursquare.com/")
        print("Flickr link = http://flickr.com/")
        print("StumbleUpon link = http://stumbleupon.com/")
        print("Dribbble link = http://dribbble.com/")
        print("Goodreads link = http://goodreads.com/")
        print("Flipboard link = http://flipboard.com/")
        print("Quora link = http://quora.com/")
        print("QuoraSpaces link = http://spaces.quora.com/")
        print("Groupon link = http://groupon.com/")
        print("Wane-lo link = http://wanelo.com/")
        print("Shopify link = http://shopify.com/")
    elif cleaned_question == "exit":
        break
    elif cleaned_question == "quit":
        break
    else:
        print("I didn't understand that. Please try again.")
